id: AA22F46F9
base_file: f4A40.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:03:33.071716
  last_modified_at: 2022-06-05 20:03:33.071724
